### ISSUE TITLE
How does the plugin work: difference between delimiter regexp / delimiter insert

### ISSUE THREAD

**Issue by flothesof** [julienr/pycharm-cellmode#11]
Hi,

I'm enjoying your plugin but have a quick question.
The options look like this for me:
![image](https://user-images.githubusercontent.com/2360669/92000892-564f1500-ed3e-11ea-9a49-145619aed34e.png)
I'm confused by the fact that there are two strings to configure:
- a regexp that should match a valid delimiter 
- something else?

To be clearer: I thought the logic is "if this regexp matches, then this is a delimiter that should start a new cell". What does the delimiter itself do?

Thank you in advance for your help.

Florian

**Comment by flothesof** [comment]
Ah I think I've got it now: 
- the insert is for when the user does *shift + enter*
- the regexp delimits cells by themselves

I think it would still be useful to add some details about this in the plugin.
@julienr, would you accept a PR for a more detailed description?

Cheers
Florian

**Comment by julienr** [comment]
Thank you for the issue and sorry for the late reply.
I think your explanation is correct and I would be happy to accept a PR for
it.
Thanks !

**Comment by julienr** [comment]
Fixed by #15
