### ISSUE TITLE
Cannot install PythonCellMode plugin for Pycharm on Mac

### ISSUE THREAD

**Issue by julienr** [julienr/pycharm-cellmode#4]
Reported by a user :

> Couldn’t install PythonCellMode plugin for Pycharm on my Mac.
> Tried both version 1.0 and 1.1.
> Has this issue been reported before?
> I tried to update Java, but got a message shown in a screenshot at the bottom of this letter.

![2018-01-14 10 21 06](https://user-images.githubusercontent.com/506602/35559586-5af16bee-05ab-11e8-8340-09588c2778bd.png)

> Translates from russian to «Couldn’t launch file … Check for messages in Console program».

![2018-01-14 10 26 28](https://user-images.githubusercontent.com/506602/35559608-6c3c710a-05ab-11e8-8745-afcf77736f7f.png)
![2018-01-14 11 34 56](https://user-images.githubusercontent.com/506602/35559610-6e060af0-05ab-11e8-945e-b83a3075f521.png)

**Comment by julienr** [comment]
So first thing, from the error message, it looks like you're trying to run the .jar. I don't think you can install pycharm plugin that way, you should go through pycharm preference pane (see below).


I tried to reproduce on my OSX machine and it works. I have pycharm 2017.3.3 :

![screen shot 2018-01-30 at 10 51 48](https://user-images.githubusercontent.com/506602/35559887-21147dfc-05ac-11e8-88f4-be53b77f8371.png)

Two questions :
- Which version of pycharm are you using ? 
- Are you installing through "Pycharm->Preferences->Plugin" ? This should look like this

![screen shot 2018-01-30 at 10 57 46](https://user-images.githubusercontent.com/506602/35560001-6dc7ed00-05ac-11e8-8f04-7ad269d53620.png)

**Comment by timurhamzin** [comment]
Thank you, Julien, it worked! It would be great if there was a link to installation instructions at the plugin page, do you agree?

**Comment by julienr** [comment]
@timurhamzin good suggestion, just did that now. Thanks !
